export {
  DEFAULT_SPATIAL_SCALE_PROFILE,
  IDENTITY_QUATERNION,
  LOCAL_FORWARD,
  LOCAL_RIGHT,
  LOCAL_UP,
  ZERO_VECTOR,
  addVectors,
  applyQuaternion,
  clonePose,
  cloneQuaternion,
  cloneVector3,
  finiteNumber,
  isNonZeroVector,
  multiplyQuaternions,
  normalizeDirection,
  normalizePose,
  normalizeQuaternion,
  normalizeScaleProfile,
  normalizeVector3,
  positiveFinite,
  quaternionFromAxisAngle,
  rotateLocal,
  scaleVector,
  subtractVectors,
  vectorLength,
} from './math.js';
export {
  icrsDirectionToTargetPc,
  icrsToRaDec,
  projectEquirectangular,
  raDecDistanceToIcrs,
  raDecToIcrsDirection,
  resolveSpatialTarget,
} from './coordinates.js';
export {
  createDirectSpatialMotionModel,
  createFlyToSpatialMotionModel,
  createInertialSpatialMotionModel,
  createThrustSpatialMotionModel,
} from './motion.js';
export {
  buildSpatialOrbitalInsertRoute,
  buildSpatialPolylineRoute,
  computeSpatialLookAtOrientation,
  createLookAtSpatialMotionModel,
  createOrbitSpatialMotionModel,
  createOrbitalInsertSpatialMotionModel,
  createRouteFollowSpatialMotionModel,
  createSpatialNavigationAutomation,
  deriveSpatialOrbitAngle,
  sampleSpatialPolylineRoutePosition,
} from './navigation.js';
